#
###################################
# Site wide configuration
####################################
#
title:       "Kev and Lisa's wedding"
description: 'July 30 at our home in The Blue Mountains'
url:         http://lisaandkev.ca/


#
###################################
# Jekyll configuration
####################################
#
timezone:          Americas/Toronto
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Kevin Walsh and Lisa Pottier
  avatar: avatar.jpg
  job: "PHP & Ruby Developer"
  # bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  email: kevinjosephwalsh@gmail.com
  # disqus-shortname: renyuanzblog
  # twitter: alittlered3 #username
  #facebook: username
  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: renyuanz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
